version: 2
mergeable:
  - when: 'pull_request.*, pull_request_review.*'
    name: 'Draft check'
    validate:
      - do: payload
        pull_request:
          draft:
            boolean:
              match: false
    pass:
      name: Approvals check
      validate:
        - do: approvals
          min:
            count: 1
          block:
            changes_requested: true
          limit:
            users:
              - ALanovaya
              - PavlushaSource
              - AlexShmak
        - do: description
          no_empty:
            enabled: true
            message: Description matter and should not be empty. Provide detail with **what** was changed, **why** it was changed, and **how** it was changed.
    fail:
      - do: comment
        payload:
          body: This PR is STILL a draft!
